[tool.poetry]
name = "em-sim"
version = "0.1.0"
description = "Electromagnetic Epistemic Modeling Framework - A framework for electromagnetic consciousness simulation"
authors = ["Kevin Kull (KVNAI - Kuonirad)"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numpy = "1.26.3"
scipy = "1.12.0"
torch = "2.0.1"
qiskit-algorithms = "0.3.1"
qiskit-terra = "0.45.0"  # Pin to match qiskit version

[tool.poetry.group.mpi]
optional = true

[tool.poetry.group.mpi.dependencies]
mpi4py = "^3.1.5"
qutip = "^5.1.1"
cupy-cuda12x = "^13.3.0"
h5py = "^3.12.1"
qiskit = "0.45.0"
qiskit-terra = "0.45.0"  # Pin to match qiskit version
qiskit-nature = "^0.7.2"
qiskit-aer = "0.12.0"
qiskit-algorithms = "0.3.1"
matplotlib = "^3.8.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
black = "^25.1.0"
isort = "^6.0.0"
flake8 = "^7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ["py38"]
include = "\\.pyi?$"
exclude = '''
/(
    \\.git
  | \\.hg
  | \\.mypy_cache
  | \\.tox
  | \\.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
