name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PYTHON_VERSION: "3.11.7"
      POETRY_VERSION: "1.7.1"

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenmpi-dev openmpi-bin \
            libhdf5-dev hdf5-tools \
            libgmp-dev cmake \
            build-essential gfortran
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: 'x64'
          cache: 'pip'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
          pipx install poetry==${{ env.POETRY_VERSION }}

      - name: Configure Poetry
        run: |
          poetry env use ${{ env.pythonLocation }}/bin/python
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          poetry install --with mpi --extras mpi --no-interaction --sync
        env:
          PYTHON_VERSION: "3.11.7"
          POETRY_VERSION: "1.7.1"
          HDF5_DIR: /usr/include/hdf5/serial
          DEBIAN_FRONTEND: noninteractive

      - name: Validate MPI
        run: |
          mpirun --version
          poetry run python -c "import mpi4py; print(mpi4py.get_config())"

      - name: Run tests
        run: |
          poetry run pytest --cov=src/em_sim --cov-report=xml
        env:
          PYTHONPATH: ${{ env.pythonLocation }}/bin:$PYTHONPATH

      - name: Check formatting
        if: success()
        run: |
          poetry run black --check .
          poetry run isort --check-only .
          poetry run flake8 .
        env:
          BLACK_CACHE_DIR: .cache/black
          ISORT_CACHE_DIR: .cache/isort
